import { LegalPageLayout } from './LegalPageLayout';
import { SEO } from '../SEO';

export function DisclaimerPage() {
  return (
    <LegalPageLayout title="AI Professional Disclaimer" lastUpdated="Version 2.4">
      <SEO title="AI Disclaimer" description="Doctoringo AI is not a substitute for professional legal counsel. Read our disclaimer." url="/disclaimer" />
      <h2>Important Notice</h2>
      <p>
        Doctoringo AI is an artificial intelligence-powered legal research assistant. Please read
        this disclaimer carefully before using the Service.
      </p>

      <h2>1. Not Legal Advice</h2>
      <p>
        The information provided by Doctoringo AI does <strong>not</strong> constitute legal advice.
        The Service is designed to assist with legal research, document drafting, and information
        gathering. It is not a substitute for professional legal counsel.
      </p>
      <p>
        Always consult with a qualified attorney or legal professional before making legal
        decisions based on information obtained through this Service.
      </p>

      <h2>2. No Attorney-Client Relationship</h2>
      <p>
        Use of Doctoringo AI does not create an attorney-client relationship between you and
        Doctoringo AI or its operators. The Service provides automated research assistance
        and should be treated as a research tool, not a legal advisor.
      </p>

      <h2>3. Accuracy and Limitations</h2>
      <p>
        While we strive for accuracy, Doctoringo AI may:
      </p>
      <ul>
        <li>Provide information that is incomplete, outdated, or contextually inappropriate.</li>
        <li>Generate documents that require review and modification by a legal professional.</li>
        <li>Misinterpret the nuances of your specific legal situation.</li>
        <li>Reference laws or regulations that may have been amended or repealed.</li>
      </ul>
      <p>
        Users are responsible for verifying all information and legal references provided by
        the Service before relying on them.
      </p>

      <h2>4. Jurisdictional Scope</h2>
      <p>
        Doctoringo AI primarily focuses on Georgian law (საქართველოს კანონმდებლობა) through
        integration with matsne.gov.ge. While the Service may provide information about other
        jurisdictions, accuracy and completeness may vary. Always verify jurisdictional
        applicability of any legal information.
      </p>

      <h2>5. Document Generation</h2>
      <p>
        Court forms and legal documents generated by Doctoringo AI are based on standard templates
        and AI-assisted data filling. These documents:
      </p>
      <ul>
        <li>Should be reviewed by a qualified legal professional before submission.</li>
        <li>May not account for all procedural requirements of your specific court or jurisdiction.</li>
        <li>Are provided as drafts and may require modifications.</li>
      </ul>

      <h2>6. AI Model Limitations</h2>
      <p>
        Doctoringo AI uses advanced language models (Google Gemini, OpenAI) that may occasionally
        generate incorrect or misleading information ("hallucinations"). The Service includes
        RAG (Retrieval-Augmented Generation) technology to ground responses in verified legal
        sources, but no AI system is infallible.
      </p>

      <h2>7. Professional Responsibility</h2>
      <p>
        Legal professionals using Doctoringo AI remain fully responsible for:
      </p>
      <ul>
        <li>Verifying all legal citations and references.</li>
        <li>Ensuring compliance with professional ethics and conduct rules.</li>
        <li>Reviewing and approving all documents before filing or distribution.</li>
        <li>Exercising independent professional judgment in all matters.</li>
      </ul>

      <h2>8. Limitation of Liability</h2>
      <p>
        Doctoringo AI and its operators shall not be liable for any direct, indirect, incidental,
        consequential, or punitive damages arising from the use of the Service, including but
        not limited to reliance on AI-generated legal information, missed deadlines, or
        incorrect legal filings.
      </p>

      <h2>9. Contact</h2>
      <p>
        For questions about this disclaimer, contact us at{' '}
        <a href="mailto:knowhowaiassistant@gmail.com">knowhowaiassistant@gmail.com</a>.
      </p>
    </LegalPageLayout>
  );
}
